### ISSUE TITLE
publish_action SDK ERROR

### ISSUE THREAD

**Issue by akhilrajrsahithi** [sohaibilyas/facebook-php-sdk-v5#10]
Dear sohaibilyas,
while I trying to post a link to my wall with using your code **post-on-user-timeline.php ,**
I got this SDK ERROR:
**Facebook SDK returned an error: Unable to convert response from Graph to a GraphEdge because the response does not look like a GraphEdge. Try using GraphNodeFactory::makeGraphNode() instead.
what should I change in my code , to post on my timeline** ?

**Comment by sohaibilyas** [comment]
To fix the error you just have to replace getGraphEdge with getGraphNode on result but even though if the error is showing up it should post on user wall.

**Comment by akhilrajrsahithi** [comment]
Thanks dear,
Even though the error 
**Facebook SDK returned an error: Unable to convert response from Graph to a GraphEdge because the response does not look like a GraphEdge. Try using GraphNodeFactory::makeGraphNode() instead.**
is shown, app posting link on my wall.  
And then I replaced _getGraphEdge_ with _getGraphNode_ on result.  So now it posting on my wall and I am getting response id .
should I create **form** for enter _user  message_. . Am using app in demo mode, and I pre defined _access_token_  manually. ( I generated **user access token** with _public_actions_ **permission** from **Graph API Explorer** tool. 
what will be the difference if my app got successfully reviewed from facebook.

Thanks for your help. 

I am reached here only because of your great tutorial . you are great .

**Comment by sohaibilyas** [comment]
To get approval from Facebook is a process unknown to me but I made a video on that topic please search on YouTube and it's also in my playlist I guess it's video 27 so watch that video to learn the process and achieve the right way of sending application for approval and for access token if you read the code that you copied first I'm getting user's token and then making it default token so every Graph API request will be made on logged in user's behalf as with the right approach.
