### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CrashOverBR** [sohaibilyas/facebook-php-sdk-v5#2]
Facebook SDK returned an error: Cross-site request forgery validation failed. Required param "state" missing.

**Comment by sohaibilyas** [comment]
Please use the same website URL in the app settings and in the script too I mean make sure of every single character even www and non www version and also have a look at https and http URL, I repeat it has be to exactly the same.

**Comment by MrSki92** [comment]
Thanks already solved the issue :) btw your github examples are great!

-----Original Message-----
