### ISSUE TITLE
Facebook SDK returned an error:

### ISSUE THREAD

**Issue by amitgora27** [sohaibilyas/facebook-php-sdk-v5#5]
when i using your code with facebook latest sdk for website login then it is showing this error

**Facebook SDK returned an error:**

and nothing showing after this error. so please check your code with facebook latest version it seem to be related the state return ID.

Thanks
Amit

**Comment by sohaibilyas** [comment]
This is not enough to debug the error! Please be more specific it should also tell you the reason.
