### ISSUE TITLE
For Sale Items Posts in Groups

### ISSUE THREAD

**Issue by jamesmorris7** [sohaibilyas/facebook-php-sdk-v5#7]
Groups now have a "sell your item" button/function. Is there an update coming soon to post "for sale items" as well as mark them as "sold". Facebook remind you often to mark these things sold so they don't sit out there indefinitely, so I'm looking for a way to manage those with a CRUD like interface, but not sure how to access these types of posts. Thanks in advance.

**Comment by sohaibilyas** [comment]
Unfortunately till now there is nothing updated in official Facebook Graph API on that feature.
